export const SENDER = { name: 'Gaurav Jadhav', email: 'hello@iamgaurav.online' };
export const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

function frame(title, eyebrow, content, preheader) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title></head><body style="margin:0;background:#edf0f6;color:#17191e;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${preheader}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 14px"><table role="presentation" width="560" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;background:#ffffff"><tr><td style="background:#1d4fff;padding:25px 32px;color:#fff"><span style="font-size:25px;font-weight:bold;letter-spacing:-2px">gj.</span><span style="float:right;font-size:11px;letter-spacing:1px;padding-top:9px">A CONVERSATION BEGINS</span></td></tr><tr><td style="padding:38px 32px"><p style="font-family:monospace;font-size:11px;letter-spacing:1px;color:#626670;margin:0 0 20px">${eyebrow}</p><h1 style="font-size:36px;font-weight:500;line-height:1.15;letter-spacing:-1.5px;margin:0 0 26px">${title}</h1>${content}<hr style="border:0;border-top:1px solid #dcdfe5;margin:30px 0 22px"><p style="font-family:Georgia,serif;font-style:italic;font-size:25px;margin:0 0 6px">Gaurav Jadhav</p><p style="font-size:12px;color:#626670;margin:0">AI &amp; product engineer · Mumbai, India</p></td></tr><tr><td style="padding:20px 32px;background:#f8f9fb;font-size:11px;line-height:1.7;color:#626670">Sent in response to a message on <a href="https://jadhavgaurav.github.io/#contact" style="color:#1d4fff">my portfolio</a>. No mailing list. Just a conversation.</td></tr></table></td></tr></table></body></html>`;
}
export function thankYouEmail() {
  // Keep user-authored message content out of automatic replies to prevent relay abuse.
  return frame('Good things start with a hello.', 'MESSAGE RECEIVED / THANK YOU', '<p style="font-size:16px;line-height:1.8">Hi there,</p><p style="font-size:16px;line-height:1.8">Thanks for reaching out. Your message is in my inbox, and I appreciate you taking the time to write.</p><p style="font-size:16px;line-height:1.8">I\'ll read it and get back to you personally. If there\'s anything else you\'d like to add, just reply to this email.</p><p style="font-size:16px;line-height:1.8">Talk soon,<br>Gaurav</p>', 'Thanks for reaching out. I look forward to reading your message.');
}
export function notificationEmail({ name, email, message }) {
  const body = `<p style="font-size:15px;line-height:1.8"><strong>From:</strong> ${escapeHTML(name)}<br><strong>Email:</strong> <a href="mailto:${escapeHTML(email)}" style="color:#1d4fff">${escapeHTML(email)}</a></p><div style="padding:20px;background:#f8f9fb;font-size:15px;line-height:1.8;white-space:pre-wrap;overflow-wrap:anywhere">${escapeHTML(message)}</div><p style="font-size:12px;line-height:1.7;color:#626670">Use the email link above to reply to the visitor. The automatic thank-you comes from hello@iamgaurav.online.</p>`;
  return frame('A new conversation.', 'PORTFOLIO / NEW MESSAGE', body, 'A visitor sent a message through your portfolio.');
}
